"""empty message

Revision ID: 69b83ea1d979
Revises: 
Create Date: 2017-05-09 18:12:20.930802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b83ea1d979'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('gmt_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('passwd', sa.String(length=128), nullable=True),
    sa.Column('passwd_hash', sa.String(length=32), nullable=True),
    sa.Column('is_teacher', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('gmt_modified', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    op.drop_table('user')
    # ### end Alembic commands ###
