"""empty message

Revision ID: b45572fab999
Revises: 69b83ea1d979
Create Date: 2017-05-14 20:56:15.936532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45572fab999'
down_revision = '69b83ea1d979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('gmt_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmt_created', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('gmt_modified', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('mem', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem')
    op.drop_table('course')
    # ### end Alembic commands ###
